name: Build and Push Docker Images

on:
  push:
    tags: ["v*"]
  pull_request:
    branches: [main]

env:
  DOCKERHUB_IMAGE: yzqzy/trade-signal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Web 镜像的元数据
      - name: Extract metadata for Web Docker
        id: meta-web
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_IMAGE }}-web
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix=,suffix=,format=short

      # Core 镜像的元数据
      - name: Extract metadata for Core Docker
        id: meta-core
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_IMAGE }}-core
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix=,suffix=,format=short

      # 构建和推送 Web 镜像
      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          target: web
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}
          cache-from: type=gha,scope=web
          cache-to: type=gha,mode=max,scope=web

      # 构建和推送 Core 镜像
      - name: Build and push Core image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          target: core
          tags: ${{ steps.meta-core.outputs.tags }}
          labels: ${{ steps.meta-core.outputs.labels }}
          cache-from: type=gha,scope=core
          cache-to: type=gha,mode=max,scope=core
